cookie:
  expiry_days: 30
  key: "critical thinking make me cry"
  name: chocolate
credentials:
  usernames:
    aaaa:
      email: 2@gmail.com
      first_name: aaaaa
      last_name: aaaaa
      logged_in: false
      password: $2b$12$xlmQ9eDGGTvpDA8DlmZL/uzEXYb4qDCCklDUQtDKlxkC30weoPClm
      password_hint: '1'
      roles:
      - user
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: false
      password: $2b$12$RYUxfcij98OarrKhnSj0qellQR2jvP8v3zrldkNuP0yj.SxUSDeca
      roles:
      - admin
      - editor
      - viewer
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      first_name: Rebecca
      last_name: Briggs
      logged_in: false
      password: $2b$12$L1kGHSTI1aBnh/P5YmFnj.GbITxIiJFOgqQ12P5rqWX49vdYv56W.
      roles:
      - viewer
    sam:
      email: 1@gmail.com
      first_name: sam
      last_name: sam
      logged_in: false
      password: $2b$12$8DXL/SrQA7F7PIIfWkKK0OdQ35D3omXDaoBE65uBgtGhrSsxJIR2a
      password_hint: '1'
      roles:
      - user
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
