cookie:
  expiry_days: 30
  key: critical thinking make me cry
  name: chocolate
credentials:
  usernames:
    aaaa:
      email: 2@gmail.com
      first_name: aaaaa
      last_name: aaaaa
      logged_in: false
      password: $2b$12$xlmQ9eDGGTvpDA8DlmZL/uzEXYb4qDCCklDUQtDKlxkC30weoPClm
      password_hint: '1'
      roles:
      - user
    cavell:
      email: Cavell@email.com
      first_name: Cavell
      last_name: Lim
      logged_in: false
      password: $2b$12$dfpP0q/1vYy752Mxp4ZxieT96F4Hh8/dqsLZbloxWxV55rFp9MP0e
      password_hint: P@55w0rd
      roles:
      - user
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: false
      password: $2b$12$RYUxfcij98OarrKhnSj0qellQR2jvP8v3zrldkNuP0yj.SxUSDeca
      roles:
      - admin
      - editor
      - viewer
    lee:
      email: Lee@email.com
      first_name: Chester
      last_name: Lee
      logged_in: false
      password: $2b$12$O2RR0FMx56FABzbQN.N6Dee8n0MgvvFwby9P7j3MXgrljyim.xVDO
      password_hint: P@55w0rd
      roles:
      - user
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      first_name: Rebecca
      last_name: Briggs
      logged_in: false
      password: $2b$12$L1kGHSTI1aBnh/P5YmFnj.GbITxIiJFOgqQ12P5rqWX49vdYv56W.
      roles:
      - viewer
    sam:
      email: 1@gmail.com
      first_name: sam
      last_name: sam
      logged_in: false
      password: $2b$12$8DXL/SrQA7F7PIIfWkKK0OdQ35D3omXDaoBE65uBgtGhrSsxJIR2a
      password_hint: '1'
      roles:
      - user
    test:
      email: Test@email.com
      first_name: Tester
      last_name: Tester
      logged_in: false
      password: $2b$12$L4w82gFSk0h4yAeBokNAP.6oVVlf4r9EXeIK/ACOqqajAcgfLHyt2
      password_hint: P@55w0rd
      roles:
      - user
    tester2:
      email: Tester2@email.com
      first_name: TesterTwo
      last_name: TesterTwo
      logged_in: false
      password: $2b$12$QO.vREvEHwhAte8mgOlX/Ot.72qm3vHB/ZNwPuvvQFSQ0WeIMCQGa
      password_hint: P@55w0rd
      roles:
      - user
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - melsby@gmail.com
